namespace: renatoalmeidaoliveira

name: netero

version: 1.1.4

readme: README.md

authors:
- Renato Almeida de Oliveira <renato.a.oliveira@pm.me>



description: Netero is a network orchestration module, that encasulates the PeeringDB API, BGPQ3 , git commit , git push.

license_file: 'LICENSE'

tags: ['peeringdb','networking','git','gogs','repository']

dependencies: {}

repository: https://github.com/renatoalmeidaoliveira/netero

documentation: https://netero.renatooliveira.eng.br/

homepage: https://netero.renatooliveira.eng.br/

issues: https://github.com/renatoalmeidaoliveira/netero/issues
